<?php
// Register Custom Post Type

function custom_post_type() {

	$labels = array(
		'name'                  => _x( 'Playlists', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'Playlist', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Playlists', 'text_domain' ),
		'name_admin_bar'        => __( 'Playlist', 'text_domain' ),
		'archives'              => __( 'Playlist Archives', 'text_domain' ),
		'attributes'            => __( 'Playlist Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Playlist:', 'text_domain' ),
		'all_items'             => __( 'All Playlists', 'text_domain' ),
		'add_new_item'          => __( 'Add New Playlist', 'text_domain' ),
		'add_new'               => __( 'Add New', 'text_domain' ),
		'new_item'              => __( 'New Playlist', 'text_domain' ),
		'edit_item'             => __( 'Edit Playlist', 'text_domain' ),
		'update_item'           => __( 'Update Playlist', 'text_domain' ),
		'view_item'             => __( 'View Playlist', 'text_domain' ),
		'view_items'            => __( 'View Playlists', 'text_domain' ),
		'search_items'          => __( 'Search Playlist', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Playlist', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Playlist', 'text_domain' ),
		'items_list'            => __( 'Items list', 'text_domain' ),
		'items_list_navigation' => __( 'Items list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter items list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Post Type', 'text_domain' ),
		'description'           => __( 'Post Type Description', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title','thumbnail', 'excerpt'),
		'taxonomies'            => array( 'category'),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'playlist', $args );
		$labels = array(
		'name'                  => _x( 'Recipes', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'Recipe', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Recipes', 'text_domain' ),
		'name_admin_bar'        => __( 'Recipe', 'text_domain' ),
		'archives'              => __( 'Recipe Archives', 'text_domain' ),
		'attributes'            => __( 'Recipe Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Recipe:', 'text_domain' ),
		'all_items'             => __( 'All Recipes', 'text_domain' ),
		'add_new_item'          => __( 'Add New Recipe', 'text_domain' ),
		'add_new'               => __( 'Add New', 'text_domain' ),
		'new_item'              => __( 'New Recipe', 'text_domain' ),
		'edit_item'             => __( 'Edit Recipe', 'text_domain' ),
		'update_item'           => __( 'Update Recipe', 'text_domain' ),
		'view_item'             => __( 'View Recipe', 'text_domain' ),
		'view_items'            => __( 'View Recipes', 'text_domain' ),
		'search_items'          => __( 'Search Recipe', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Recipe', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Recipe', 'text_domain' ),
		'items_list'            => __( 'Recipes list', 'text_domain' ),
		'items_list_navigation' => __( 'Recipes list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter recipes list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Post Type', 'text_domain' ),
		'description'           => __( 'Post Type Description', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'thumbnail', 'excerpt'),
		'taxonomies'            => array( 'category'),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'recipe', $args );

		$labels = array(
		'name'                  => _x( 'Zones', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'Zone', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Zones', 'text_domain' ),
		'name_admin_bar'        => __( 'Zone', 'text_domain' ),
		'archives'              => __( 'Zone Archives', 'text_domain' ),
		'attributes'            => __( 'Zone Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Zone:', 'text_domain' ),
		'all_items'             => __( 'All Zones', 'text_domain' ),
		'add_new_item'          => __( 'Add New Zone', 'text_domain' ),
		'add_new'               => __( 'Add New', 'text_domain' ),
		'new_item'              => __( 'New Zone', 'text_domain' ),
		'edit_item'             => __( 'Edit Zone', 'text_domain' ),
		'update_item'           => __( 'Update Zone', 'text_domain' ),
		'view_item'             => __( 'View Zone', 'text_domain' ),
		'view_items'            => __( 'View Zones', 'text_domain' ),
		'search_items'          => __( 'Search Zone', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Zone', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Zone', 'text_domain' ),
		'items_list'            => __( 'Items list', 'text_domain' ),
		'items_list_navigation' => __( 'Items list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter items list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Post Type', 'text_domain' ),
		'description'           => __( 'Post Type Description', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array('title'),
		'taxonomies'            => array(),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'zone', $args );

}
add_action( 'init', 'custom_post_type', 0 );
?>